blank_issues_enabled: false
contact_links:
  - name: QEMU upstream issues
    url: https://gitlab.com/qemu-project/qemu/-/issues
    about: If this issue is about upstream QEMU, please report it there.
